version: "3.7"
services:
  mongo:
    container_name: mongo_database
    image: mongo
    ports:
      - "27017:27017"
    networks: 
      - maneko-network 
  
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_maneko
    image: frontend:latest
    ports:
      - "3000:8080"
    networks: 
      - maneko-network 

  backend:
    build: 
      context: ./backend/source/API
      dockerfile: Dockerfile 
    container_name: backend_maneko
    image: backend:latest 
    ports:
      - "5000:5000"
      - "5001:5001"
    networks: 
      - maneko-network 


networks : 
  maneko-network:    